[versions]
agp = "8.9.2"
kotlin = "2.1.20"

junit = "4.13.2"

androidx_junit = "1.2.1"

[libraries]
## Test Libraries
junit = { group = "junit", name = "junit", version.ref = "junit" }
## AndroidTest Libraries
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx_junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
## Kotlin Plugins
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

